version: '3.8'

services:
  # 1. The Database
  mysqldb:
    image: mysql:8.0
    container_name: project_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: project_manager
    ports:
      - "3307:3306" 
    volumes:
      - db_data:/var/lib/mysql

  # 2. Database Viewer 
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysqldb

volumes:
  db_data: